### ISSUE TITLE
Whitestar Engine Improved Error Handling

### ISSUE THREAD

**Issue by briandoconnor** [SeqWare/seqware#309]
The Whitestar engine needs improved handling of errors.  Here's a failed workflow's output:

<pre>
Performing launch of workflow 'SangerPancancerCgpCnIndelSnvStr' version '1.0.5'
[--plugin, net.sourceforge.seqware.pipeline.plugins.BundleManager, --, --install-dir-only, --bundle, /workflows/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr
_1.0.5_SeqWare_1.1.0-alpha.5, --out, /tmp/bundle_manager7668397891120713991out]
Installing Bundle (Working Directory Only)
Bundle: /workflows/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.5_SeqWare_1.1.0-alpha.5
Added 'SangerPancancerCgpCnIndelSnvStr' (SWID: 1)
Bundle Has Been Installed to the MetaDB and Provisioned to /workflows/Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.5_SeqWare_1.1.0-alpha.5!
[--plugin, io.seqware.pipeline.plugins.WorkflowScheduler, --, --workflow-accession, 1, --host, 800af462310e, --out, /tmp/scheduler3198893700935340770out, --i, 
/ini_files/c78a5e63-4897-4489-814b-dc6ae31de64a.ini, --workflow-engine, whitestar-parallel, --no-meta-db]
Created workflow run with SWID: 113
[--plugin, io.seqware.pipeline.plugins.WorkflowLauncher, --, --launch-scheduled, 113]
[2015/03/21 08:08:46] | Number of submitted workflows: 1
Working Run: 113
Valid run by host check: 113
Launching via new launcher: 113
Using working directory: /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761
[2015/03/21 08:08:49] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/start_0-runner.sh
[2015/03/21 08:08:51] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/mark_start_1-runner.sh
[2015/03/21 08:08:51] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/mark_start_2-runner.sh
...
[2015/03/21 08:32:02] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/ASCAT_allele_count_111-runner.sh
[2015/03/21 08:32:02] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/cgpPindel_input_119-runner.sh
[2015/03/21 08:32:02] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/cgpPindel_input_120-runner.sh
[2015/03/21 08:32:02] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/BRASS_input_150-runner.sh
[2015/03/21 08:32:02] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/BRASS_input_149-runner.sh
[2015/03/21 17:59:24] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/packageGenotype_12-runner.sh
[2015/03/21 17:59:24] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/cgpPindel_pindel_121-runner.sh
[2015/03/21 17:59:24] | [2015/03/21 17:59:24] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/BRASS_group_151-runner.sh
Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/ASCAT_ascat_112-runner.sh
[2015/03/21 17:59:24] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/bbAllele_merge_60-runner.sh
[2015/03/21 17:59:24] | Running command: bash /datastore/oozie-6ff6060a-5473-4e94-b5bd-c95dd2030761/generated-scripts/binCount_merge_109-runner.sh
[SeqWare Pipeline] FATAL [2015/03/21 19:00:46] | java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[SeqWare Pipeline] FATAL [2015/03/21 19:00:46] | Workflowrun launch with accession: 113 failed
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at io.seqware.pipeline.engines.whitestar.WhiteStarWorkflowEngine.runWorkflow(WhiteStarWorkflowEngine.java:134)
        at io.seqware.pipeline.plugins.WorkflowLauncher.launchNewWorkflow(WorkflowLauncher.java:244)
        at io.seqware.pipeline.plugins.WorkflowLauncher.launchScheduledWorkflows(WorkflowLauncher.java:170)
        at io.seqware.pipeline.plugins.WorkflowLauncher.do_run(WorkflowLauncher.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.evaluateReturn(PluginRunner.java:311)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.invokePluginMethods(PluginRunner.java:289)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.run(PluginRunner.java:109)
        at io.seqware.pipeline.plugins.WorkflowLifecycle.runPlugin(WorkflowLifecycle.java:248)
        at io.seqware.pipeline.plugins.WorkflowLifecycle.runWorkflowLauncherPlugin(WorkflowLifecycle.java:237)
        at io.seqware.pipeline.plugins.WorkflowLifecycle.do_run(WorkflowLifecycle.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.evaluateReturn(PluginRunner.java:311)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.invokePluginMethods(PluginRunner.java:289)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.run(PluginRunner.java:109)
        at net.sourceforge.seqware.pipeline.runner.PluginRunner.main(PluginRunner.java:64)
        at io.seqware.cli.Main.run(Main.java:227)
        at io.seqware.cli.Main.bundleLaunch(Main.java:448)
        at io.seqware.cli.Main.bundle(Main.java:603)
        at io.seqware.cli.Main.main(Main.java:1939)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
        at java.util.concurrent.FutureTask.get(FutureTask.java:111)
        at io.seqware.pipeline.engines.whitestar.WhiteStarWorkflowEngine.runWorkflow(WhiteStarWorkflowEngine.java:130)
        ... 25 more
Caused by: java.lang.RuntimeException: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at net.sourceforge.seqware.common.util.Rethrow.rethrow(Rethrow.java:26)
        at io.seqware.pipeline.engines.whitestar.WhiteStarWorkflowEngine$ExecutionThread.call(WhiteStarWorkflowEngine.java:193)
        at io.seqware.pipeline.engines.whitestar.WhiteStarWorkflowEngine$ExecutionThread.call(WhiteStarWorkflowEngine.java:150)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.seqware.pipeline.engines.whitestar.WhiteStarWorkflowEngine$ExecutionThread.call(WhiteStarWorkflowEngine.java:190)
        ... 6 more
[--plugin, io.seqware.pipeline.plugins.WorkflowWatcher, --, --workflow-run-accession, 113]
[--plugin, net.sourceforge.seqware.pipeline.plugins.WorkflowStatusChecker, --, --workflow-run-accession, 113]
</pre>

From this output it looks like Whitestar is failing for an unknown reason. It's actually step 121 but you would have no way to know this by looking at it.

Since many people are using whitestar now for running PanCancer workflows it's worth improving the error output.  My list of suggestions in order of priority most to least important:

* a clear message that says the step that specifically failed
* removing the stacktrace for whitestar which isn't helpful here and simply reporting the failed steps
* ideally the stderr/stdout of the failed steps would be reproduced here along with the command called. this would be extremely helpful in debugging what went wrong
* the above should be controlled by the "seqware-output-lines-number" option for specifying the number of lines to propagate back
* for script that redirect their stderr/stdout to their own logs there's nothing that you can really do.  But by showing the command executed at least it's clear why no stderr/stdout output has been propogated back

**Comment by denis-yuen** [comment]
Agreed. I think we should be able to do this in two parts. 
1) An upgrade to the the WorkflowLauncher to produce a better message about which step failed when running Whitestar.
2) An call to and possibly an upgrade to WorkflowRunReporter to return information on stderr/stdout controlled by seqware-output-lines-number

**Comment by denis-yuen** [comment]
Addressed in 1.1.1
